
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "dlnp2", email = "hideta7.dev@gmail.com"},
]
dependencies = [
    "h5py>=3.8.0",
    "qdrant-client>=0.11.9",
]
requires-python = ">=3.10"
license = {text = "MIT"}
